services:
  - type: web
    name: my-python-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend      # Specify the backend directory
    plan: free
